name = "SigmoidalProgramming"
uuid = "ce2a0656-6bed-5c64-9e01-e7b1ac833b80"
keywords = ["sigmoidal programming", "branch and bound"]
license = "MIT"
version = "1.0"

[deps]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
julia = "1.3"
Clp = "0.8"
DataStructures = "0.18"
GLPK = "0.14"
JuMP = "0.21"
MathOptInterface = "0.9"
